env:
  repo:            "https://github.com/farrukh90/artemis"
  app_version:     "4.0.0"
  repo_region:     "us-central1"
  project_id:      "${{ secrets.PROJECT_ID }}"
  app_name:        "artemis"
  tag_new_version: ${GITHUB_SHA}

# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
 

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  image-build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3



 
      # Clone a repo using ENV we give in first line
      - name: Clone a repo
        run: |
          git clone ${{ env.repo }}


      # switch branches
      - name: Switch Branches
        working-directory: ${{ env.app_name }}
        run: |
          git checkout ${{ env.app_version }}
          ls -l



      # Remove old version wehn we have multiple images
      - name: Remove Old Images
        working-directory: ${{ env.app_name }}
        run: |
          echo "hello"
         #docker image prune -af



      # Build Image 
      - name: Build Image
        working-directory: ${{ env.app_name }}
        run: |
          # docker image prune -af
          docker build -t ${{ env.app_name }}:${{ env.app_version }}   . 


      # create our own new version image 
      - name: Tag Image
        working-directory: ${{ env.app_name }}
        run: |
          docker image tag ${{ env.app_name }}:${{ env.app_version }} ${{ env.repo_region }}-docker.pkg.dev/${{ env.project_id }}/${{ env.app_name }}/${{ env.app_name }}:${{ env.tag_new_version }}     


      # Runs a single command using the runners shell
      - name: Verify Gcloud installation
        run: gcloud version 


      # Authenticate to GCP
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.SERVICE_ACCOUNT }}'

      # Authenticate to my repository
      - name: Authenticate to repository
        run: |
          gcloud auth configure-docker  ${{ env.repo_region }}-docker.pkg.dev

          


      # push the image to repository
      - name: Image push
        working-directory: ${{ env.app_name }}
        run: |
          docker push ${{ env.repo_region }}-docker.pkg.dev/${{ env.project_id }}/${{ env.app_name }}/${{ env.app_name }}:${{ env.tag_new_version }}



